sudo: true
language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - sudo apt-get install libxmlsec1 libxmlsec1-dev
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install coverage
  - pip install coveralls
before_script:
  - cp sampleproj/manage.py manage.py
  - python manage.py migrate --noinput --settings=sampleproj.settings.travis
script:
  - pycodestyle mdot_rest/ --exclude=migrations
  - coverage run --source=mdot_rest/ --omit=mdot_rest/admin.py,mdot_rest/migrations/* manage.py test mdot_rest --settings=sampleproj.settings.travis
after_script:
  - coveralls
