sudo: false
language: python
python:
  - "2.7"
  - "2.6"
install: 
  - pip install .
before_script: 
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - python manage.py test
