version: '3.4'

services:
  app:
    restart: always
    container_name: mdot-rest
    build:
      context: .
      dockerfile: Dockerfile
      target: app-container
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./mdot-rest:/app/mdot-rest
    ports:
      - "${PORT:-8000}:8000"
    environment:
      ENV: localdev
      AUTH: ${AUTH:-SAML_MOCK}
