ingress:
    enabled: true
    tls:
      mdot-rest:
        secretName: test-api.mdot.uw.edu-ingress-cert
        hosts:
          - test-api.mdot.uw.edu
    hosts:
      mdot-rest:
        host: test-api.mdot.uw.edu
        paths:
          - "/"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"
  lifecycle:
    enabled: true
    preStop:
      enabled: true
  affinity:
     podsSpanNodes: true
  readiness:
    enabled: true
  externalService:
    enabled: true
    name: mdot-rest-db-service
    type: ClusterIP
    serviceAddress: 104.198.109.182  # change to match db
    servicePort: 3306
  database:
    engine: mysql
    name: mdot_rest_test
    hostname: mdot-rest-db-service
    secretName: test-api.mdot.uw.edu-sql-secrets
  repo: mdot-rest
  instance: test
  image:
    repository: registry.hub.docker.com/acait/mdot-rest
    tag: IMAGE_TAG
  memcached:
    enabled: false
  gcsCredentials:
    mounted: true
    secretName: test-api.mdot.uw.edu-gc-service-credentials
  cronjob:
    enabled: false
  environmentVariables:
    - name: ENV
      value: test
    - name: AUTH
      value: SAML
    - name: SAML_ENTITY_ID
      value: https://test-api.mdot.uw.edu/saml2
    - name: CLUSTER_CNAME
      value: test-api.mdot.uw.edu
    - name: ADMIN_AUTHZ_GROUP
      value: 'u_test_admin'
  externalSecrets:
    enabled: true
    secrets:
      - name: test-api.mdot.uw.edu-secrets
        externalKey: axdd/kv/data/mdot-rest/test/secrets
        data:
          - name: django-secret
            property: django-secret
          - name: google-analytics-key
            property: google-analytics-key
          - name: storage-project-id
            property: storage-project-id
          - name: storage-bucket-name
            property: storage-bucket-name
      - name: test-api.mdot.uw.edu-sql-secrets
        externalKey: axdd/kv/data/mdot-rest/test/sql-secrets
        data:
          - name: username
            property: username
          - name: password
            property: password
      - name: test-api.mdot.uw.edu-ic-certs
        externalKey: axdd/kv/data/mdot-rest/test/ic-certs
        data:
          - name: test-api.mdot.uw.edu-ic.cert
            property: test-api.mdot.uw.edu-ic.cert
      - name: test-api.mdot.uw.edu-uw-idp-cert
        externalKey: axdd/kv/data/idp-cert
        data:
          - name: uw-idp-cert
            property: cert
      - name: test-api.mdot.uw.edu-gc-service-credentials
        externalKey: axdd/kv/data/test/mdot-rest/gc-service-credentials
        data:
          - name: credentials.json
            property: credentials.json
  environmentVariablesSecrets:
    djangoSecret:
      name: DJANGO_SECRET
      secretName: test-api.mdot.uw.edu-secrets
      secretKey: django-secret
    googleAnalyticsKey:
      name: GOOGLE_ANALYTICS_KEY
      secretName: test-api.mdot.uw.edu-secrets
      secretKey: google-analytics-key
    storageProjectId:
      name: STORAGE_PROJECT_ID
      secretName: test-api.mdot.uw.edu-secrets
      secretKey: storage-project-id
    storageBucketName:
      name: STORAGE_BUCKET_NAME
      secretName: test-api.mdot.uw.edu-secrets
      secretKey: storage-bucket-name
    samlSPCert:
      name: SP_CERT
      secretName: test-api.mdot.uw.edu-ic-certs
      secretKey: test-api.mdot.uw.edu-ic.cert
    samlIDPCert:
      name: IDP_CERT
      secretName: test-api.mdot.uw.edu-uw-idp-cert
      secretKey: uw-idp-cert