# Generated by Django 2.1.15 on 2020-05-28 18:58

from django.db import migrations, models
import django.db.models.deletion
import mdot_rest.optimizedpngfield


class Migration(migrations.Migration):

    dependencies = [
        ('mdot_rest', '0010_auto_20150917_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intendedaudience',
            options={'default_related_name': 'intended_audiences'},
        ),
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'default_related_name': 'resource_links'},
        ),
        migrations.AlterField(
            model_name='intendedaudience',
            name='resource',
            field=models.ManyToManyField(related_name='intended_audiences', to='mdot_rest.UWResource'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='link_type',
            field=models.CharField(choices=[('AND', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('WIP', 'Windows Phone')], max_length=3),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='mdot_rest.UWResource'),
        ),
        migrations.AlterField(
            model_name='uwresource',
            name='image',
            field=mdot_rest.optimizedpngfield.OptimizedPNGImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
